import pygame

world = ['                                                                             ',
         '                                                                             ',
         '                                                                             ',
         '                                                                             ',
         '                                                                             ',
         '                                                                             ',
         '                                                                             ',
         '                                                                             ',
         '                                                                             ',
         '                                                                             ',
         '                                                                             ',
         '                          IJJJK                                              ',
         '                         IAHHHEK                                             ',
         '                         CBHHHHEK                                            ',
         '                          CDDDDDF                                            ',
         '                                                                             ',
         '                                                                             ',
         '                                                                             ',
         '                                                                             ',
         '                                                                             ',
         '                                                                             ',
         '                                                                             ',
         '                                                                             ',
         '                                                                             ',
         '                                                                             ',
         '                                                                             ',]